trigger:
    branches:
        include:
            - '*' # Run on all branches

resources:
    -   repo: self

stages:
    -   stage: Test
        displayName: Test
        jobs:
            -   job: Test
                displayName: Debricked Vulnerabilities scan
                pool:
                    vmImage: 'ubuntu-latest'
                steps:
                    -   script: |
                            env | awk -F '=' 'BEGIN { OFS = "=" } {gsub(/ /,"",$1)} {print $0}' > env.list
                            docker run -v $HOME:$HOME --env-file ./env.list --entrypoint "/azure-devops.sh" debricked/debricked-scan:latest
                        env:
                            USERNAME: $(DEBRICKED_USERNAME)
                            PASSWORD: $(DEBRICKED_PASSWORD)
                            DEBRICKED_API_URI: https://staging.debricked.com